### ISSUE TITLE
Rename to L.TileLayer.Bing

### ISSUE THREAD

**Issue by IvanSanchez** [digidem/leaflet-bing-layer#1]
As per the naming convention in the [Leaflet plugin guide](https://github.com/Leaflet/Leaflet/blob/master/PLUGIN-GUIDE.md#plugin-api)

**Comment by gmaclennan** [comment]
Fixed in https://github.com/gmaclennan/leaflet-bing-layer/commit/0b3b0c5c6485032e7d7092a06548b8ab80577683 and https://github.com/gmaclennan/leaflet-bing-layer/commit/5094950725f97cf0868362e4b57cda6f30b6944b
