### ISSUE TITLE
Different market

### ISSUE THREAD

**Issue by resuly** [digidem/leaflet-bing-layer#10]
Thank you for your great job.

I noticed that  leaflet-bing-layer does not support well for other countries (culture:"zh-Hans"), but the following codes from bing dev center shows another way in China area:
`<script type='text/javascript' src='https://cn.bing.com/mapspreview/sdk/mapcontrol?branch=release&callback=loadMapScenario' async defer></script>` 
(The default market setting there is `var market = "zh-CN";`)

How can I request layers from different market? Thank you.

**Comment by gmaclennan** [comment]
According to the Bing REST API docs there is a `culture` setting, that you can set as an option: https://github.com/gmaclennan/leaflet-bing-layer#parameters

If this does not work I'm not sure, this may be a limitation of the Imagery REST API. The code you share is from the JavaScript API, which is different.

(btw the culture setting only affects the map tiles themselves, all the controls on the map are rendered by Leaflet, so any localization would need to be done there)

**Comment by gmaclennan** [comment]
Assuming this is resolved.
