### ISSUE TITLE
Correcting "© AND" in Bing attributions

### ISSUE THREAD

**Issue by RHenningsgard** [digidem/leaflet-bing-layer#12]
Like your project!  First used it today, found that Bing map attributes include "© AND".  Here's a one-line change which filters it out.  Warning: REQUIRES that you save leaflet-bing-layer.js in UNICODE, to preserve the copyright character.  I'm sure some clever person will figure out a better way.

This goes in the _getAttributions function:

```
      if (provider.attribution != '© AND') { //"© AND" was showing up in the attribution
        attributions.push(provider.attribution);
      }  
```

**Comment by jengeb-rbb** [comment]
Why would you filter it?

**Comment by RHenningsgard** [comment]
I would filter it because I was a numbskull and thought it was a bug... not knowing of the map company "AND."
--------------------------------------------
On Mon, 4/24/17, jengeb-rbb <notifications@github.com> wrote:

 Subject: Re: [gmaclennan/leaflet-bing-layer] Correcting "© AND" in Bing attributions (#12)
 To: "gmaclennan/leaflet-bing-layer" <leaflet-bing-layer@noreply.github.com>
 Cc: "RHenningsgard" <rhenningsgard@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Monday, April 24, 2017, 7:17 AM
 
 Why would you filter it?
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by jengeb-rbb** [comment]
Thanks for your quick reply. 
So I think this issue can be closed, right?

**Comment by RHenningsgard** [comment]
Oh absolutely yes!  

Thanks again!

Rob---

--------------------------------------------
On Mon, 4/24/17, jengeb-rbb <notifications@github.com> wrote:

 Subject: Re: [gmaclennan/leaflet-bing-layer] Correcting "© AND" in Bing attributions (#12)
 To: "gmaclennan/leaflet-bing-layer" <leaflet-bing-layer@noreply.github.com>
 Cc: "RHenningsgard" <rhenningsgard@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Monday, April 24, 2017, 9:40 AM
 
 Thanks for your quick reply.
 
 So I think this issue can be closed, right?
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
