### ISSUE TITLE
is retina support

### ISSUE THREAD

**Issue by emreesirik** [digidem/leaflet-bing-layer#15]
has bing map retina support, can it retrieve 2x images? Because there is space between tiles at retina
![ekran alintisi](https://cloud.githubusercontent.com/assets/7847917/21161375/eec065ec-c190-11e6-8771-50b49bf47241.PNG)

**Comment by gmaclennan** [comment]
Hi @emreesirik I can't seen any documentation of a high dpi (retina) option for the [Bing Imagery API ](https://msdn.microsoft.com/en-us/library/ff701716.aspx) which is what this plugin uses.

The gaps you see are likely an issue with leaflet, not this plugin, which just provides tiles to Leaflet to render.
