### ISSUE TITLE
Street name isn't rendered correctly on the map

### ISSUE THREAD

**Issue by jengeb** [digidem/leaflet-bing-layer#18]
I use Bing Maps Layer in a map-application. 'Goethestraße' (52.51623 13.51613) is not rendered correctly on the map (G**ö**thestraße).  

![screenshot from 2017-04-04 14-32-03](https://cloud.githubusercontent.com/assets/3831683/24657003/ff51cdc2-1944-11e7-87e3-bc087313e6e6.png)

Bing shows the proper street name:

![screenshot from 2017-04-04 14-39-06](https://cloud.githubusercontent.com/assets/3831683/24657006/0217ee06-1945-11e7-9876-e2924bd9a92b.png)

Do you know the reason for this issue?

**Comment by gmaclennan** [comment]
This is due to the `options.culture` parameter which defaults to `en_US`, see in the README: https://github.com/gmaclennan/leaflet-bing-layer#parameters

The possible options are documented here: https://msdn.microsoft.com/en-us/library/ff701709.aspx
