### ISSUE TITLE
Bing Maps moving from V7 to V8

### ISSUE THREAD

**Issue by gargipingale** [digidem/leaflet-bing-layer#19]
I use leaflet bing layer plugin. I have been notified that Bing Maps is moving from V7 to V8 version on June 30, 2017.  Does this plugin take that into consideration ?

**Comment by gmaclennan** [comment]
Hi @gargipingale, the change from Bing Maps V7 to V8 refers to the Bing Javascript API. This plugin does not use that API. It uses the Imagery API from the Bing REST API: https://msdn.microsoft.com/en-us/library/ff701716.aspx

The plugin will not be affected by the deprecation of Bing Maps V7.
