### ISSUE TITLE
New version to npm?

### ISSUE THREAD

**Issue by landswellsong** [digidem/leaflet-bing-layer#22]
I wonder if it's possible for you to publish the latest changes as `3.1.1` or something? I'm particularly interested in https://github.com/digidem/leaflet-bing-layer/commit/636ba59ca8b189822ec2babfcc2f85a4c748eb5e .

**Comment by gmaclennan** [comment]
done in 3.2.0

**Comment by landswellsong** [comment]
Wow thank you so much!
