### ISSUE TITLE
wrong demo link in repository

### ISSUE THREAD

**Issue by spatialhast** [digidem/leaflet-bing-layer#23]
there is wrong link on demo http://gmaclennan.github.io/leaflet-bing-layer/
![image](https://user-images.githubusercontent.com/3269617/29133285-a13b7d86-7d3b-11e7-840e-5cc12bbfa056.png)
please change into http://digidem.github.io/leaflet-bing-layer/

**Comment by gmaclennan** [comment]
fixed
