### ISSUE TITLE
difference to bing plugin from shramov?

### ISSUE THREAD

**Issue by seyfro** [digidem/leaflet-bing-layer#3]
As I am currently using the bing plugin from shramov (https://github.com/shramov/leaflet-plugins/blob/master/layer/tile/Bing.js) I wonder why you decided to build a new bing plugin. Did you experience any limitations with that plugin?

**Comment by gmaclennan** [comment]
Thanks @robertharm, good question, I actually didn't come across that plugin when I was searching around for how to use Bing tiles with Leaflet. Doesn't look like there is much difference, other than this plugin only being for Leaflet v1.0.0 and up.
