### ISSUE TITLE
Custom Styling

### ISSUE THREAD

**Issue by rpascal** [digidem/leaflet-bing-layer#33]
Hello,

I am trying to look into doing custom styling on my map. I know it is possible to do using Bing Maps V8 and REST Services,  as shown here [https://msdn.microsoft.com/en-us/library/mt823632.aspx](url). Is it possible to do the same sort of thing here? I have been looking all over and have not been able to find a solution. I know there are the predefined imagerySets but I would like to make something custom if I could. If you know whether or not this is possible that would be very helpful thank you!

**Comment by gmaclennan** [comment]
I just added this is in `v3.3.0`, just released

**Comment by rpascal** [comment]
Thank you for updating but that is not exactly what I meant. Do you know if it is possible to do something similar to
![image](https://user-images.githubusercontent.com/9251639/37421635-2ae49a50-2790-11e8-937c-5e870689da94.png)
So give the custom styles to the url request (various styles given on this page [(page)](https://msdn.microsoft.com/en-us/library/mt823632.aspx)). That way I could define a custom style outside of the predefined Microsoft imagerySets.

**Comment by gmaclennan** [comment]
Yes that’s it. Pass one of those style strings as `options.style` and it should work, but only if you use the `options.imagerySet` which supports dynamic tiles (the ones that end with `onDemand`)

**Comment by gmaclennan** [comment]
Let me know I you have any suggestions for improving the Readme on this. Feel free to edit the readme and submit a PR

**Comment by rpascal** [comment]
I see it now my apologies! Thank you very much I'll try that tonight!
