### ISSUE TITLE
How to set maxZoom for interpolate after 18

### ISSUE THREAD

**Issue by ppKrauss** [digidem/leaflet-bing-layer#39]
Hi, thanks to offer leaflet-bing-layer, it is great!  

I am new here, trying to "zoom in" (by interpolation if not possible more tham 18)... 
```js
    var BING_KEY = 'AuhiCJHlGzhg93IqUH_oCpl_-ZUrIE6SPftlyGYUvr9Amx5nzA-WqGcPquyFZl4L'

    var map = L.map('map').setView([1.2862100, 103.8541900], 18)
    map.options.maxZoom = 20;
    map.options.maxNativeZoom = 18;

    var bingLayer = L.tileLayer.bing(BING_KEY).addTo(map)
```
It is **not working** (blank image), after 18 (clicking "+")

**Comment by ppKrauss** [comment]
Hello?

**Comment by TNLuke** [comment]
I believe there is a previous [open issue](https://github.com/digidem/leaflet-bing-layer/issues/8).

[This comment](https://github.com/digidem/leaflet-bing-layer/issues/8#issuecomment-351350993) references a workaround but I have not verified.

**Comment by ppKrauss** [comment]
Thanks @TNLuke (!). Now I am using this clues, https://stackoverflow.com/a/53883145/287948
and it is working fine!
