### ISSUE TITLE
It doesn't work when setting  a value to the option.culture.

### ISSUE THREAD

**Issue by MoAIDeBo** [digidem/leaflet-bing-layer#40]
Hi
This is the code

`let map = L.map('map').setView([27.991369850942526,86.88915252685547], 3);`
`L.tileLayer.bing({
        bingMapsKey,
        culture: "zh-Hans"
    }).appTo(map);
`
There was nothing changed . Am I misunderstand this property?  ^_^

**Comment by KatBu** [comment]
I tried changing culture in library leaflet-bing-layer.js  and faced the same problem. The language does not change.

**Comment by gmaclennan** [comment]
Unfortunately it looks like Bing does not support this language for the Imagery API: https://msdn.microsoft.com/en-us/library/hh441729.aspx and I _think_ that for the map tiles they are coming from the Imagery API, not the Locations API.

**Comment by moory** [comment]
I also have this problem. :( 
It doesn't work.
(zh-CN,zh-HK)

**Comment by gmaclennan** [comment]
As in the link in the previous comment, Bing does not have maps imagery for these cultural codes. Closing this for now, since there is unfortunately nothing we can do about it.

**Comment by MoAIDeBo** [comment]
@gmaclennan I've got it, thank you for your reply.
