### ISSUE TITLE
AerialWithLabels layer with culture: 'ru' doesn't work.

### ISSUE THREAD

**Issue by nextstopsun** [digidem/leaflet-bing-layer#5]
I'm trying to add a bing `AerialWithLabels` type layer with Russian labels. I've tried to set culture option to `'ru'`, or `'RU-ru'`, or `'ru-RU'` - and neither did work. The layer is always displayed with english labels. How can this be fixed?

**Comment by haoliangyu** [comment]
Unfortunately, Russian seems to be unsupported in the Bing imagery service. Source: [https://msdn.microsoft.com/en-us/library/hh441729.aspx](https://msdn.microsoft.com/en-us/library/hh441729.aspx)

**Comment by rbrundritt** [comment]
At this time, the Bing Maps REST services are using the older static Bing Maps tiles which is limited to about 25 or so cultures. The newer Bing Maps controls use a new dynamic tile service which supports 117 cultures. The Bing Maps REST services will likely be updated to return the dynamic tile URL sometime over the next six months.

**Comment by gmaclennan** [comment]
Closing since this seems to be a Bing issue.
