### ISSUE TITLE
Does not work in secured URL

### ISSUE THREAD

**Issue by AnushreeAcharjee** [digidem/leaflet-bing-layer#7]
If the page is opened using https instead of http, the map does not open. If I manually go to the file leaflet-bing-layer.min.js and change http to https, it works fine.
How do I configure it in L.tileLayer.bing so that my app works both with http and https?

**Comment by cedricr** [comment]
https://github.com/gmaclennan/leaflet-bing-layer/pull/6 probably fixes it

**Comment by gmaclennan** [comment]
Finally merged #6, should work now.
