### ISSUE TITLE
Does this work with Bing Maps V8?

### ISSUE THREAD

**Issue by CostinTanasoiu** [digidem/leaflet-bing-layer#9]
Bing Maps version 8 was released earlier this year.

**Comment by CostinTanasoiu** [comment]
I just checked your code and it still uses the 'virtualearth' script URL, which means it is still for V7. 

There's a V7 to V8 migration plan here:
http://social.technet.microsoft.com/wiki/contents/articles/34563.bing-maps-v7-to-v8-migration-guide.aspx

More documentation, including the V8 API Reference:
https://msdn.microsoft.com/en-us/library/mt712542.aspx

Also, Bing Maps V8 interactive SDK:
http://www.bing.com/api/maps/sdk/mapcontrol/isdk#overview

**Comment by jefbarn** [comment]
This plugin just pulls the static tiles, and I don't think the URL for those changed with V8, so it doesn't seem to need an update.
https://msdn.microsoft.com/en-us/library/ff701724.aspx

**Comment by rbrundritt** [comment]
As Jeff mentioned, this project uses the Bing Maps REST services which still use a virtualearth.net domain. Bing Maps V8 is a JavaScript library that you would use as an alternate to leaflet, not as an extension to it. The Bing Maps REST services expose most of the raw data that the Bing Maps controls use. In this case the Bing Maps tiles. Recommend closing this issue.

**Comment by CostinTanasoiu** [comment]
That makes sense, thanks!
